# Generated by Django 3.1.1 on 2020-09-13 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Literature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Supersection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upho.section')),
            ],
        ),
        migrations.CreateModel(
            name='Theory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_page', models.PositiveSmallIntegerField(default=0)),
                ('end_page', models.PositiveSmallIntegerField(default=0)),
                ('difficulty', models.PositiveSmallIntegerField(default=0)),
                ('chosen', models.BooleanField(default=False)),
                ('literature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upho.literature')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upho.theme')),
            ],
        ),
        migrations.AddField(
            model_name='section',
            name='supersection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upho.supersection'),
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theme', to='upho.theme')),
                ('parent_theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirement', to='upho.theme')),
            ],
        ),
        migrations.CreateModel(
            name='Problems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10)),
                ('difficulty', models.PositiveSmallIntegerField(default=0)),
                ('chosen', models.BooleanField(default=False)),
                ('literature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upho.literature')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upho.theme')),
            ],
        ),
    ]
