# Generated by Django 3.1.1 on 2020-09-14 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upho', '0002_theme_full_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problems',
            name='difficulty',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='theory',
            name='difficulty',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
