# Generated by Django 3.1.1 on 2020-09-14 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upho', '0003_auto_20200914_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='literature',
            name='short_title',
            field=models.CharField(default='ok', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='literature',
            name='year',
            field=models.PositiveSmallIntegerField(default=2),
            preserve_default=False,
        ),
    ]
