# Generated by Django 3.1.1 on 2020-09-14 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upho', '0004_auto_20200914_2246'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Problems',
            new_name='Problem',
        ),
    ]
