# Generated by Django 3.1.1 on 2020-09-14 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upho', '0005_auto_20200915_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='difficulty',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
