# Generated by Django 3.1.1 on 2020-09-16 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upho', '0006_auto_20200915_0129'),
    ]

    operations = [
        migrations.CreateModel(
            name='OlympEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('location', models.CharField(choices=[('Region', (('KYIV', 'м. Київ'), ('LVIV', 'м. Львів'), ('ODESA', 'м. Одеса'))), ('Institution', (('RL', 'Рішельєвський ліцей'),))], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Olympiad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('olymp_type', models.CharField(choices=[('national', 'Всеукраїнська олімпіада з фізики'), ('regional', 'Обласна олімпіада з фізики')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='OlympFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.PositiveSmallIntegerField(choices=[(8, '8 клас'), (9, '9 клас'), (10, '10 клас'), (11, '11 клас')])),
                ('tour', models.CharField(choices=[('theory', 'Теоретичний тур'), ('exp', 'Експериментальний тур')], max_length=6)),
                ('solutions', models.BooleanField(default=False)),
                ('pdf', models.FileField(upload_to='olympiads')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upho.olympevent')),
            ],
        ),
        migrations.AddField(
            model_name='olympevent',
            name='olympiad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upho.olympiad'),
        ),
    ]
