# Generated by Django 3.1.1 on 2020-09-16 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upho', '0007_auto_20200916_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='olympevent',
            name='location',
            field=models.CharField(choices=[('Region', (('KYIV', 'м. Київ'), ('LVIV', 'м. Львів'), ('ODESA', 'м. Одеса'), ('KHERSON', 'м. Херсон'))), ('Institution', (('RL', 'Рішельєвський ліцей'),))], max_length=30),
        ),
        migrations.AlterField(
            model_name='olympfile',
            name='pdf',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='olympiad',
            name='olymp_type',
            field=models.CharField(choices=[('national', 'Всеукраїнська'), ('regional', 'Обласна')], max_length=10),
        ),
    ]
