# Generated by Django 3.1.1 on 2020-09-18 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upho', '0008_auto_20200916_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='olympevent',
            name='location',
            field=models.CharField(choices=[('KYIV', 'м. Київ'), ('LVIV', 'м. Львів'), ('ODESA', 'м. Одеса'), ('KHERSON', 'м. Херсон')], max_length=30),
        ),
        migrations.AlterField(
            model_name='olympfile',
            name='grade',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Всі класи'), (8, '8 клас'), (9, '9 клас'), (10, '10 клас'), (11, '11 клас')]),
        ),
        migrations.AlterField(
            model_name='olympfile',
            name='pdf',
            field=models.FileField(upload_to='olympiads'),
        ),
    ]
