# Generated by Django 3.1.1 on 2020-09-18 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upho', '0009_auto_20200918_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='literature',
            name='literature_type',
            field=models.CharField(choices=[('theory', 'Підручник'), ('problems', 'Задачник')], default='theory', max_length=10),
            preserve_default=False,
        ),
    ]
