# Generated by Django 3.1.1 on 2020-09-18 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upho', '0011_remove_literature_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='literature',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
