# Generated by Django 3.1.1 on 2020-09-21 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upho', '0013_auto_20200921_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='olympfile',
            name='pdf',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='problem',
            name='difficulty',
            field=models.PositiveSmallIntegerField(choices=[(0, 'novice'), (1, 'advanced'), (2, 'expert'), (3, 'math')], null=True),
        ),
        migrations.AlterField(
            model_name='theory',
            name='difficulty',
            field=models.PositiveSmallIntegerField(choices=[(0, 'novice'), (1, 'advanced'), (2, 'expert')]),
        ),
    ]
