# Generated by Django 3.1.1 on 2020-09-21 21:28

from django.db import migrations, models
import upho.models


class Migration(migrations.Migration):

    dependencies = [
        ('upho', '0014_auto_20200922_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='literature',
            name='eng_title',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='literature',
            name='pdf',
            field=models.FileField(null=True, upload_to=upho.models.Literature.literature_filename),
        ),
        migrations.AlterField(
            model_name='problem',
            name='difficulty',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Novice'), (1, 'Advanced'), (2, 'Expert'), (3, 'Math')], null=True),
        ),
        migrations.AlterField(
            model_name='theory',
            name='difficulty',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Novice'), (1, 'Advanced'), (2, 'Expert')]),
        ),
    ]
